name: cache
description: An example of using cache with jaguar
version: 0.0.1
homepage: github.com/Jaguar-dart/jaguar_cache
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_cache: ^0.1.1
  jaguar: ^0.6.7
  jaguar_serializer: ^0.3.16
  mongo_dart:
  jaguar_mongo:
  jaguar_serializer_mongo:
  jaguar_json: ^0.1.3
  jaguar_client:

dev_dependencies:
  test: ^0.12.0
